- name: "Playbook test 2 - touch file"
  hosts: localhost
  connection: local
  tasks:
  - name: Ansible create file with content 
    copy:
      dest: "/tmp/jpruitt-user-data-ssm-ansible.txt"
      content: |
        jpruitt
        this file is used to test user data calling SSM to apply anisble playbook
